### PR TITLE
add support for go version >= 1.14

### PR DESCRIPTION
**Pull request by icexin**

### CODE REVIEW

**Comment by prologic** [comment]
Can we get to Go 1.16 ? 🤔

**Comment by icexin** [comment]
> Can we get to Go 1.16 ? 🤔

Yes! The test is mainly done on go1.16.

**Comment by prologic** [comment]
So I can build this now on macOS with Go 1.16 ? 🤔

**Comment by icexin** [comment]
> So I can build this now on macOS with Go 1.16 ? 🤔

Yes.

**Pull request merged**
